### PR TITLE
Implementing selection for Tag and Probe + fixing bug in logic

### PR DESCRIPTION
**Pull request by michelif**
This is a PR:
- Integrates a couple of methods to give the possibility to run on single electron datasets inverting the electron veto. This is needed for MVA validation on Z->ee, and useful for Tag and Probe, debugging with electrons...
- Fixes a bug in applying scale and smearings. I think they were wrong, I made a fix and validated with the Z peak

### CODE REVIEW

**Comment by andreypz** [comment]
Hi Francesco,

Could you point us to the lines where you fix the smearing bug. How serious is it? Maybe we have to rerun with the fix and see how much is the effect on the result.

**Comment by michelif** [comment]
Hi Andrey,
sure, I just thought it was too late.

So there are two things, one minor and one major.

- Minor: These two flags https://github.com/ResonantHbbHgg/bbggTools/pull/36/files#diff-4ad25ccf83c1cab7451e520147444331R99 were set to 1 while they have to be set to 0 like the comment says. But it seems to me (checking the history) that when the final ntuples were produced they were correctly set to 0 (correct me if I'm wrong), and then updated by mistake.

- Major: you smear the photon with the bbggPhotonCorrector class and you update the PhotonCandidate collection. But this doesn't update the diphotonCandidate class, so when you get the diphotonCandidate lorentz vector you have the unsmeared one. Which means that diphotonCandidate.M() gives you the unsmeared mass. The fix is trivial, just get the photoncandidate vectors (which are properly smeared) and sum them. It is implemented here https://github.com/ResonantHbbHgg/bbggTools/pull/36/files#diff-33c9606f1a6eb60cb584a6c3b4dccd6aR1139 of course it would be better to update the diphotonCandidate class but I didn't manage.

The effect of this is that:
- The energy of single photons is correctly smeared (if the two flags of the minor issue were set to 0 as I think)
- The diphoton invariant mass used in the analysis is NOT smeared.
I noticed it by doing data/MC comparison on Zee, since I saw variables for single photons were ok but the Z peak was off. I upload here a slide, with the comparison (statistics is not huge since i had to reproduce the samples
[micheli_checkPR_20180212.pdf] (https://github.com/ResonantHbbHgg/bbggTools/files/1716465/micheli_checkPR_20180212.pdf)
).

Of course given the analysis sensitivity the effect is not huge (also,I guess most photons are in EB, where the scale is ~right, there is just a 1% smearing missing) but clearly it's a bug, and will have some effect going into direction of less sensitivity since the MC is not smeared in the diphoton mass distribution.

**Comment by andreypz** [comment]
Thanks for the full explanation, now it's clear.

Whether it's too late to fix in the paper, I don't know. But I think we could check the effect by producing a fixed signal samples. As I understand this would mostly(only?) affect the MC.

Since, I'll be away for 10 days, I ask @mgouzevi  to have look at this PR and merge it. 
Then, if either you or Maxime could give me the fixed flat trees for non-res signal samples, I would rerun the limits.

**Comment by michelif** [comment]
Hi Andrey,
in principle, it affects both data and MC (scale correction is for data, smearing correction is for MC). 
Trying to have an idea on what could be the effect, my guess is just that since the analysis would select mostly EB photons, where the scale is ~right and smearing is 1-2%, the final net effect is the same as you get if you take the MC and smear it by 1-2%. But of course it's just a rough estimate in my mind (so the sigma is big :-) ) and it is also not 100% true that scale is ok in EB and EE is negligible, as you said we should rerun (not sure I can do it in short time scale,but we can discuss)

**Comment by mgouzevi** [comment]
I would need a better explanation. Could we cluster wednesday?

**Comment by michelif** [comment]
I can on Wednesday (at least on skype). long story short is mass is NOT smeared, if you change this line it is https://github.com/ResonantHbbHgg/bbggTools/pull/36/files#diff-33c9606f1a6eb60cb584a6c3b4dccd6aR1139

**Comment by andreypz** [comment]
Actually, I think we could check the effect without reproducing the flat trees, because we also store individual photons 4-momenta (which should be smeared correctly I think). I'll try to do this sometime this week.
(I won't be able to meet though)

**Pull request merged**
